# Derive tool and parameters in two passes.
# Reduces token usage, but increases response time due to an extra request.
double_pass_derive = false

# The number of tries to derive a tool call.
num_derive_tries = 3

[llm]
api = "ollama"
query_fmt = "Using the context {context} derive a tool call for the following query. {query}"

[llm.ollama]
base_url = "http://localhost:11434"
model = "qwen2.5"

[llm.open_ai]
base_url = "https://api.openai.com/v1"
key = "$OPENAI_API_KEY"
model = "gpt-4o-mini"
